/**
 * The `/r/*` fronting, generated rather than written twice.
 *
 * A captured report is delivered as `https://screener.gomintro.com/r/<run>/<token>`, proxied to
 * the object in the public `reports` bucket. **This is an indirection layer, not a header hack.**
 * The header falls out of it for free; the reasons it exists are that a link with no expiry has to
 * outlive decisions about where bytes are kept, and that an underwriting partner should not be
 * handed the Supabase project ref.
 *
 * ## Why a generator and not four lines of `netlify.toml`
 *
 * Because `/r/` would then be spelled in two places — the config that serves it and the code that
 * composes the link — and a rule expressed twice is a rule that will differ (D-034). That is not a
 * hypothetical here: the last URL shape stated in two places had the worker composing
 * `/comment/<token>` while the page read `?comment=<token>`, and it would have delivered a
 * merchant to a sign-in screen holding the only token that report would ever have.
 *
 * So `REPORT_LINK_PATH` is the single owner and this emits the config from it. `netlify.toml`
 * contains no `/r/` at all.
 *
 * The project ref comes from the build environment for the same reason. Hard-coding it would put
 * a deployment-specific identifier in the repository and give every branch deploy production's
 * storage.
 *
 * ## Why the SPA fallback moved here too
 *
 * Ordering, and it is not a preference. Netlify evaluates `netlify.toml` redirects **before**
 * `_redirects`, and first match wins. The catch-all `/*  →  /index.html` in `netlify.toml` would
 * therefore swallow `/r/*` and serve the analyst app in place of every delivered report. Both
 * rules have to live in one file so the order between them is visible and enforced.
 */

import type { Plugin } from 'vite';
/*
  This import is why `apps/web`'s build script compiles the engine first.

      "build": "tsc --build ../../packages/engine && vite build"

  **Do not remove that step, and do not resolve this import any other way.** Vite pre-bundles its
  own config with esbuild before any of the config's own settings apply, so `resolve.alias` — which
  points `@mintro/engine` at `src/browser.ts` for the *app* bundle — does not govern this line. It
  falls through to ordinary package resolution, and the engine's `exports` names one entry:
  `./dist/src/index.js`. No dist, no entry, and the build dies with *"Failed to resolve entry for
  package @mintro/engine"* before `VITE_SUPABASE_URL` is ever read.

  That is exactly how this shipped broken. A local build and CI both passed, because both ran in a
  tree where something had already compiled the engine — CI's `npm run check` does it as a side
  effect of typechecking before the tests. Netlify starts clean, and the first real deploy failed.

  The prerequisite is real and permanent: a config that imports a workspace package needs that
  package built. It is declared in the build command rather than inherited from whatever happened
  to run first.
*/
import { REPORT_LINK_PATH } from '@mintro/engine';

export interface ProxyConfig {
  /**
   * The worker's public origin, e.g. `https://mintro-screener-worker.fly.dev`.
   *
   * **Not the storage origin.** Supabase serves public HTML as `text/plain` with a sandbox CSP
   * whatever mimetype is stored, which strips the inline styles and inline captures a
   * self-contained report is made of. The worker serves the bytes with headers we control.
   */
  readonly workerOrigin: string | undefined;
  /** True on a Netlify build, where a missing origin is fatal rather than irrelevant. */
  readonly onNetlify: boolean;
}

/**
 * The `_redirects` file.
 *
 * `:splat` captures `<run>/<token>` and the `.html` is appended here, because the delivered link
 * carries no extension and the stored object does. That asymmetry is deliberate — a URL handed to
 * a person should not advertise a file format — and this is the one place the two are reconciled.
 *
 * **200, never 301.** A redirect hands the storage URL to the browser, which puts it in the
 * address bar and in the reader's history: the project ref is disclosed anyway and the indirection
 * buys nothing. Proxied, the reader never learns where the bytes live.
 */
export function redirectsFile(config: ProxyConfig): string {
  const lines = [
    '# Generated by apps/web/netlifyReportProxy.ts. Do not edit.',
    '#',
    '# `/r/` is owned by REPORT_LINK_PATH in packages/engine/src/reportCapture.ts. It is not',
    '# written here by hand, and it is not in netlify.toml.',
    '',
  ];

  if (config.workerOrigin !== undefined && config.workerOrigin !== '') {
    const origin = config.workerOrigin.replace(/\/+$/, '');
    lines.push(
      '# Captured reports, served by the worker. Proxied, not redirected: a 301 would put the',
      '# worker origin in the address bar, and the link people hold should be a Mintro one.',
      `${REPORT_LINK_PATH}* ${origin}${REPORT_LINK_PATH}:splat 200`,
      '',
    );
  } else if (config.onNetlify) {
    // A deploy whose report links 404 is worse than a build that stops. Netlify is the only place
    // this file means anything, so this is where the requirement is real.
    throw new Error(
      'VITE_REPORT_ORIGIN is not set, so there is nowhere to proxy captured reports to. ' +
        `Every ${REPORT_LINK_PATH} link would 404.`,
    );
  } else {
    // A local build — `npm run web:build`, or the bundle the worker renders from. There is no
    // Netlify serving layer here, so the rule is absent rather than wrong.
    lines.push(
      '# No VITE_REPORT_ORIGIN at build time, so no report proxy. Local builds are served by the',
      "# worker's own report server, which has no Netlify layer to configure.",
      '',
    );
  }

  lines.push(
    '# The single-page app, last. Everything above must match first — this rule matches anything.',
    '/*  /index.html  200',
    '',
  );

  return lines.join('\n');
}

/**
 * The `_headers` file.
 *
 * `X-Robots-Tag` is **defence in depth and not the gate of record**. For an HTML document the
 * `<meta name="robots">` inside the captured file is the primary control, and it is the one that
 * holds if the file is ever served from somewhere other than here. This covers the case the meta
 * tag cannot: a crawler that reads headers without parsing the body.
 */
export function headersFile(): string {
  return [
    '# Generated by apps/web/netlifyReportProxy.ts. Do not edit.',
    '',
    `${REPORT_LINK_PATH}*`,
    '  X-Robots-Tag: noindex, nofollow',
    '',
  ].join('\n');
}

/** Emits both files into the build output. */
export function netlifyReportProxy(env: NodeJS.ProcessEnv = process.env): Plugin {
  const config: ProxyConfig = {
    workerOrigin: env['VITE_REPORT_ORIGIN'],
    onNetlify: env['NETLIFY'] === 'true',
  };

  return {
    name: 'mintro:netlify-report-proxy',
    apply: 'build',
    generateBundle() {
      this.emitFile({ type: 'asset', fileName: '_redirects', source: redirectsFile(config) });
      this.emitFile({ type: 'asset', fileName: '_headers', source: headersFile() });
    },
  };
}
