-- 0079 — what a draft cost to produce: attempts and token usage (D-260)
--
-- `EvaluateResult` has carried `attempts` and `usage` since the generator was written, and
-- `storeDraft` has been dropping both on the floor. They existed only on the CLI's stdout, which
-- means they existed until the terminal scrolled. The first real generation on run 9011b2d7 lost
-- exactly that way: the run happened, the draft is on the row, and how many attempts it took and
-- what it cost are unrecoverable without paying for the call a second time.
--
-- That matters beyond bookkeeping. `attempts` is the validator's own hit rate — a draft that took
-- two attempts was refused once, and the refusal is the signal that a rule is mis-drawn or the
-- prompt is unclear. D-260 already records three cases where the fix was found by reading what the
-- model did wrong; none of them would have been visible from the stored row.
--
-- ## Nullable, because zero would be a claim
--
-- Every column here is nullable and none carries a default. A row written before this migration was
-- generated by a job that did not record these numbers, and `attempts = 0` on such a row would
-- assert that no attempt was made — which is what the `run_did_not_see_storefront` guard means, and
-- it is not what happened. Null says "not recorded"; zero says "did not happen". Backfilling the
-- two existing rows with a guess is the one thing this migration must not do.
--
-- Null is also the honest value going forward wherever the vendor reported no usage: a generation
-- refused before the model was called spends nothing, and its `attempts` is a real 0 while its
-- token columns stay null.

alter table public.evaluation_drafts
  add column attempts      integer,
  add column input_tokens  integer,
  add column output_tokens integer;

-- Checks rather than `not null`: a null passes every one of these, so the two existing rows are
-- untouched and unrecorded, while a recorded value cannot be negative.
alter table public.evaluation_drafts
  add constraint evaluation_drafts_attempts_check      check (attempts is null or attempts >= 0),
  add constraint evaluation_drafts_input_tokens_check  check (input_tokens is null or input_tokens >= 0),
  add constraint evaluation_drafts_output_tokens_check check (output_tokens is null or output_tokens >= 0);

comment on column public.evaluation_drafts.attempts is
  'How many times the model was called for this draft. 0 when the generation was refused before any '
  'call; more than 1 means the validator refused an earlier answer, which is the signal worth '
  'reading. Null on rows written before 0079 — not recorded, not zero.';

comment on column public.evaluation_drafts.input_tokens is
  'Vendor-reported input tokens for the accepted answer. Null when no call was made or the vendor '
  'reported no usage.';

comment on column public.evaluation_drafts.output_tokens is
  'Vendor-reported output tokens for the accepted answer, thinking included — on an adaptive-thinking '
  'model these are not separable, and a number that silently excluded thinking would understate the '
  'cost of exactly the generations worth investigating. Null when no call was made.';
